version: "3"

services:
  ngulikdb:
    # platform: linux/amd64
    image: mysql:5.7
    container_name: ngulikdb
    environment:
      MYSQL_ROOT_PASSWORD: ${NGULIK_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NGULIK_MYSQL_DATABASE_NAME}
      MYSQL_USER: ${NGULIK_MYSQL_USER}
      MYSQL_PASSWORD: ${NGULIK_MYSQL_PASSWORD}
      MYSQL_MAX_ALLOWED_PACKET: 512M
    restart: unless-stopped
    ports:
      - "${NGULIK_MYSQL_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
  ngulikpma:
    # platform: linux/amd64
    image: phpmyadmin:latest
    container_name: ngulikpma
    environment:
      PMA_HOST: ngulikdb
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 512M
    restart: always
    ports:
      - 8082:80
    links:
      - ngulikdb
volumes:
  dbdata:
